### ISSUE TITLE
Raft issue

### ISSUE THREAD

**Issue by AlbshriAdel** [MarcoMazzoni/caliper-docker-tests#2]
I tried to use the Caliper benchmark with Quorum by using this project, which has worked perfectly with consensus algorithms supported by Quorum networks such as Istanbul and qbft. However, an error message appeared when I tried to use raft as a consensus algorithm, as shown below in fig 1. Therefore, I tried all possible solutions, but unfortunately, all attempts failed.
![error](https://user-images.githubusercontent.com/84684367/191796599-49b5bee4-15ef-405d-87d5-498d9c8f70ec.PNG)

**Comment by Jouyourin** [comment]
Hi ,  I am currently trying to reproduce this benchmarking experiment with a qbft quorum consensus, but i get this error: 

TypeError: CaliperUtils.getBuiltinAdapterPackageNames is not a function
    at Function.handler (/home/yourina/lastCaliperQ/caliper/packages/caliper-cli/lib/launch/lib/launchMaster.js:58:79)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
could you tell me how did you u make it work please!
